### ISSUE TITLE
Meadow does not honor DHCP DNS server settings

### ISSUE THREAD

**Issue by fredmbarrett** [WildernessLabs/.github#1]
When Meadow connects to a Wifi access point using DHCP, it assumes that the Default Gateway is the DNS Server source for the network, and prepends the default gateway into the dns.conf, further using it for DNS resolution:
```
MeadowApp running...
Searching dns.conf...
...found 2 entries in dns.conf:
- nameserver 10.0.1.1
- nameserver 1.1.1.1
Searching dns.conf complete.
```
However, in enterprise networks, not all default gateways act as DNS servers, and Meadow ignores or otherwise fails to process the DNS Server settings issued by a DHCP service:
```
   Connection-specific DNS Suffix  . : 8.8.8.8
   Description . . . . . . . . . . . : Realtek USB GbE Family Controller
   Physical Address. . . . . . . . . : C4-65-16-8B-CC-F4
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::2cb7:5009:1f61:8f23%20(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.0.1.142(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Friday, December 15, 2023 8:53:04 PM
   Lease Expires . . . . . . . . . . : Monday, January 1, 2024 3:19:05 PM
   Default Gateway . . . . . . . . . : 10.0.1.1
   DHCP Server . . . . . . . . . . . : 10.0.1.1
   DHCPv6 IAID . . . . . . . . . . . : 650405142
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-2C-67-C0-72-20-79-18-30-8B-DF
   DNS Servers . . . . . . . . . . . : 8.8.8.8
                                       8.8.4.4
                                       1.1.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
For proper network operation, Meadow needs to adopt the DNS Server settings issued by the DHCP Service, and not assume the Default Gateway has the ability to resolve domain names.

**Comment by jorgedevs** [comment]
Hi @fredmbarrett , can you please report this issue on our [Meadow_Isssues](https://github.com/WildernessLabs/Meadow_Issues) repo? We dont track any issues in our org's readme repository.

Thanks!
